---
constants:
  C_SPEED:  2.99792458e8  # m/s
  RHO_CRIT0_KPC3_UNITY_H: 277.536627  # multiply by h**2 in cosmology conversion
  MPC:  3.08567758149e24  # Mpc in cm
  YEAR: 31556925.2  # year in seconds

telescopes:
  MUSE:
    fov: 5
    spatial_res: 0.2
    wave_range: [4700.15, 9351.4]
    wave_res: 1.25
    lsf_fwhm: 2.51
    signal_to_noise: null
    wave_centre: 6975.775
    sbin: 64
    aperture_type: "square"
    pixel_type: "square"

cosmology:
  PLANCK15:
    Om0: 0.3075
    w0: -1.0
    wa: 0.0
    h: 0.6774


