"""Inference helpers for gradient-based modeling workflows."""

from .api import apply_params, forward, loss, value_and_grad
from .benchmark import (
    IFUCubeBenchmarkResult,
    benchmark_callable,
    benchmark_ifu_cube_optimization,
    benchmark_result_to_dict,
    estimate_array_nbytes,
)
from .calibration import (
    CalibrationSummary,
    interval_covers,
    normalized_error,
    sample_posterior_parameters,
    sbc_rank,
    sbc_rank_histogram,
    summarize_calibration,
    summarize_parameter_calibration,
)
from .checkpoint import (
    load_checkpoint,
    make_optimization_checkpoint,
    make_variational_checkpoint,
    resume_optimization_from_checkpoint,
    resume_variational_from_checkpoint,
    save_checkpoint,
)
from .experiment import (
    compare_science_run_to_baseline,
    create_science_run_baseline,
    generate_ifu_experiment_report,
    normalize_experiment_config,
    run_ifu_experiment,
    run_ifu_experiment_sequence,
    save_ifu_experiment_outputs,
    validate_ifu_experiment_inputs,
)
from .losses import combine_loss_fns, huber_data_loss, masked_gaussian_nll
from .modes import get_pipeline_name_for_mode, make_inference_pipeline
from .objective_config import build_loss_from_config, build_loss_from_user_config
from .objectives import build_ifu_cube_loss, masked_weighted_mse
from .optimize import (
    OptimizationResult,
    OptimizationState,
    optimize_ifu_cube,
    optimize_params,
)
from .parameterization import (
    IdentityTransform,
    ParameterTransform,
    SigmoidBounds,
    SoftplusLowerBound,
    VelocityZBoundsTransform,
    apply_transforms,
    build_age_metallicity_transforms,
    build_age_metallicity_velocity_transforms,
    inverse_transforms,
)
from .performance_guardrails import (
    OptimizationObjectiveThresholds,
    PerformanceCheckResult,
    RuntimeThresholds,
    VIObjectiveThresholds,
    check_ifu_optimization_guardrails,
    check_vi_guardrails,
    load_guardrail_threshold_profile,
)
from .posterior_family import (
    init_low_rank_factor,
    kl_low_rank_to_standard_normal,
    low_rank_marginal_log_std,
    sample_low_rank_gaussian,
)
from .posterior_predictive import (
    compute_residual_products,
    sample_posterior_predictive_cubes,
    summarize_masked_metrics,
    summarize_predictive_cube_samples,
)
from .priors import build_ceh_relation_prior_penalty, build_sfh_ceh_prior_penalty
from .validation import GradientComparison, compare_gradients, finite_difference_grad
from .variational import (
    VariationalResult,
    VariationalState,
    initialize_mean_field_params,
    kl_diag_gaussian_to_standard_normal,
    optimize_variational_ifu_cube,
    optimize_variational_posterior,
    sample_diag_gaussian,
)
from .vi_benchmark import (
    VIBenchmarkResult,
    benchmark_variational_inference,
    vi_benchmark_result_to_dict,
)
from .workflows import run_synthetic_science_recipe, save_science_recipe_outputs

__all__ = [
    "IdentityTransform",
    "ParameterTransform",
    "SigmoidBounds",
    "SoftplusLowerBound",
    "VelocityZBoundsTransform",
    "GradientComparison",
    "IFUCubeBenchmarkResult",
    "OptimizationResult",
    "OptimizationState",
    "OptimizationObjectiveThresholds",
    "PerformanceCheckResult",
    "RuntimeThresholds",
    "VIObjectiveThresholds",
    "VariationalResult",
    "VariationalState",
    "VIBenchmarkResult",
    "CalibrationSummary",
    "apply_params",
    "apply_transforms",
    "interval_covers",
    "normalized_error",
    "sample_posterior_parameters",
    "sbc_rank",
    "sbc_rank_histogram",
    "summarize_calibration",
    "summarize_parameter_calibration",
    "init_low_rank_factor",
    "kl_low_rank_to_standard_normal",
    "low_rank_marginal_log_std",
    "sample_low_rank_gaussian",
    "load_checkpoint",
    "make_optimization_checkpoint",
    "make_variational_checkpoint",
    "generate_ifu_experiment_report",
    "normalize_experiment_config",
    "build_age_metallicity_transforms",
    "build_age_metallicity_velocity_transforms",
    "build_ifu_cube_loss",
    "build_loss_from_config",
    "build_loss_from_user_config",
    "combine_loss_fns",
    "compare_science_run_to_baseline",
    "benchmark_callable",
    "benchmark_ifu_cube_optimization",
    "benchmark_result_to_dict",
    "compare_gradients",
    "compute_residual_products",
    "build_sfh_ceh_prior_penalty",
    "build_ceh_relation_prior_penalty",
    "check_ifu_optimization_guardrails",
    "check_vi_guardrails",
    "load_guardrail_threshold_profile",
    "estimate_array_nbytes",
    "finite_difference_grad",
    "forward",
    "get_pipeline_name_for_mode",
    "huber_data_loss",
    "inverse_transforms",
    "loss",
    "make_inference_pipeline",
    "masked_gaussian_nll",
    "masked_weighted_mse",
    "initialize_mean_field_params",
    "kl_diag_gaussian_to_standard_normal",
    "optimize_ifu_cube",
    "benchmark_variational_inference",
    "vi_benchmark_result_to_dict",
    "optimize_variational_ifu_cube",
    "optimize_variational_posterior",
    "optimize_params",
    "resume_optimization_from_checkpoint",
    "resume_variational_from_checkpoint",
    "sample_posterior_predictive_cubes",
    "sample_diag_gaussian",
    "summarize_masked_metrics",
    "summarize_predictive_cube_samples",
    "save_checkpoint",
    "create_science_run_baseline",
    "run_ifu_experiment",
    "run_ifu_experiment_sequence",
    "save_ifu_experiment_outputs",
    "validate_ifu_experiment_inputs",
    "value_and_grad",
    "run_synthetic_science_recipe",
    "save_science_recipe_outputs",
]
