templates:
  BruzualCharlot2003:
    name: "Bruzual & Charlot (2003)"
    format: "HDF5" # Format of the template
    source: "https://www.bruzual.org/bc03/"
    file_path: "BC03lr.h5" # File name of the template, stored in templates directory
    # Define the Fields in the template and their units
    # This is used to convert them to the required units
    fields: # Fields in the template and their units
    # Name defines the name of the key stored in the hdf5 file
      age:
        name: "age"
        units: "Gyr" # Age of the template
        in_log: false # If the field is stored in log scale
      metallicity:
        name: "metallicity"
        units: "Z/Zsun" # Metallicity of the template
        in_log: false # If the field is stored in log scale
      wavelength:
        name: "wavelength"
        units: "Angstrom" # Wavelength of the template
        in_log: false # If the field is stored in log scale
      flux:
        name: "flux"
        units: "Lsun/Angstrom" # Luminosity of the template
        in_log: false # If the field is stored in log scale
