calc_ifu:
  Transformers:
    rotate_galaxy:
      name: rotate_galaxy
      depends_on: null
      args: []
      kwargs:
        type: "face-on"
    # This does not work inside the pipeline since we need dynamic JAX arrays here, and its not suppoerted for jit
    # filter_particles:
    #   name: filter_particles
    #   depends_on: rotate_galaxy
    #   args: []
    #   kwargs: {}
    spaxel_assignment:
      name: spaxel_assignment
      depends_on: rotate_galaxy
      args: []
      kwargs: {}

    reshape_data:
      name: reshape_data
      depends_on: spaxel_assignment
      args: []
      kwargs: {}

    calculate_spectra:
      name: calculate_spectra
      depends_on: reshape_data
      args: []
      kwargs: {}

    scale_spectrum_by_mass:
      name: scale_spectrum_by_mass
      depends_on: calculate_spectra
      args: []
      kwargs: {}
    doppler_shift_and_resampling:
      name: doppler_shift_and_resampling
      depends_on: scale_spectrum_by_mass
      args: []
      kwargs: {}

    calculate_datacube:
      name: calculate_datacube
      depends_on: doppler_shift_and_resampling
      args: []
      kwargs: {}
    convolve_psf:
          name: convolve_psf
          depends_on: calculate_datacube
          args: []
          kwargs: {}